### ISSUE TITLE
Change About us Texts

### ISSUE THREAD

**Issue by infernotower** [particl/particl.foundation#3]
About us
The Particl Foundation is an entity created with the main purpose of supporting a blockchain based project named Particl. Particl is an open source, decentralized privacy platform built for global person to person and business to person transactions. The blockchain project offers encrypted communication tools offer unfettered access available to users worldwide.
Business
Particl provides a self-governance and privacy suite operating under a secured distributed network instead of a centralized server. This will be an attractive option for people looking to streamline small to big e-commerce businesses, as well as secure sensitive transactions. Particl project offers privacy for sensitive transactions, making it extremely difficult to be exposed to malicious attacks. In order to ensure network agreement is in place, a self-governing mechanism is set in place, giving the community authority to vote out certain decisions. In a world where security is slowly becoming more compromised, it is one of the foundation’s goals to enable the offering of competitive solutions worldwide, at the same time making it difficult for others to judge people based on their sexual orientation, religious beliefs, political views and other prejudice.
Purpose
The Foundation’s purpose is promoting and developing new technologies and applications, especially in the fields of new open and decentralized software architectures. A dominating but not exclusive focus is set on the promotion and development of the so-called Particl Protocol and the related technologies, as well as the promotion and support of applications using the Particl Protocol.
Concept
The Foundation’s mission is to promote and develop new open and decentralized software architectures, in particular the Particl protocol. The Particl platform has a self-governance functionality hardcoded into the protocol to ensure consensual decisions are met to reflect the network.

**Comment by LiteBit** [comment]
Are these taken from the Foundation prospectus?

**Comment by infernotower** [comment]
The Particl Foundation is an entity created with the main purpose of supporting a blockchain based project named Particl. Particl is an open source, decentralized privacy platform built for global person to person and business to person transactions. The blockchain project offers encrypted communication tools offer unfettered access available to users worldwide.

Please change this to:

Particl Foundation is a non-profit organisation, serving the Particl ecosystem and promoting awareness of financial privacy.

**Comment by infernotower** [comment]
Particl Foundation is a non-profit organisation, serving the Particl ecosystem and promoting awareness of financial privacy.

Purpose
The Foundation’s purpose is promoting and developing new technologies and applications, especially in the fields of new open and decentralized software architectures. A dominating but not exclusive focus is set on the promotion and development of the so-called Particl Protocol and the related technologies, as well as the promotion and support of applications using the Particl Protocol.

**Comment by AllienWorks** [comment]
@infernotower so is this the final text for the About us page?

> Particl Foundation is a non-profit organisation, serving the Particl ecosystem and promoting awareness of financial privacy.
> ## Purpose
> The Foundation’s purpose is promoting and developing new technologies and applications, especially in the fields of new open and decentralized software architectures. A dominating but not exclusive focus is set on the promotion and development of the so-called Particl Protocol and the related technologies, as well as the promotion and support of applications using the Particl Protocol.

**Comment by infernotower** [comment]
Yes, we got the consensus.
Bear in mind we might put a little bit more texts depending on the SEC memos.
